/**
 * Claude Prompt Map V2 - Character Options
 * Subject/character options for the prompt builder
 */

import { ClaudePromptOptionV2 } from './promptMapV2Types';

export const CHARACTER_OPTIONS_V2: ClaudePromptOptionV2[] = [
  {
    id: 'cyber-samurai',
    label: 'Cyber Samurai',
    description: 'Katana with plasma edge, traditional armor with holographic overlays, stoic warrior',
    tags: ['warrior', 'cyberpunk', 'japanese'],
    keywords: ['cyber samurai', 'katana', 'armor', 'holographic', 'warrior stance'],
    visual: {
      gradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
      icon: '⚔️',
      color: '#f093fb',
      particles: ['⚔️', '⚡', '💠'],
      mood: 80,
      energy: 85,
    },
  },
  {
    id: 'astral-mage',
    label: 'Astral Mage',
    description: 'Robes woven from starlight, galaxy swirling in staff, eyes glowing with cosmic power',
    tags: ['magic', 'cosmic', 'powerful'],
    keywords: ['mage', 'cosmic magic', 'starlight', 'staff', 'mystical robes'],
    visual: {
      gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      icon: '🔮',
      color: '#667eea',
      particles: ['✨', '🌟', '💫'],
      mood: 70,
      energy: 75,
    },
  },
  {
    id: 'biomech-pilot',
    label: 'Biomechanical Pilot',
    description: 'Half-organic half-machine, neural interface cables, flight suit integrated with skin',
    tags: ['scifi', 'cybernetic', 'pilot'],
    keywords: ['biomechanical', 'pilot', 'cybernetic', 'neural interface', 'integrated tech'],
    visual: {
      gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
      icon: '🤖',
      color: '#4facfe',
      particles: ['⚡', '🔷', '💠'],
      mood: 65,
      energy: 80,
    },
  },
  {
    id: 'shadow-assassin',
    label: 'Shadow Assassin',
    description: 'Dissolving into smoke, dark hood, twin obsidian daggers, only eyes visible',
    tags: ['stealth', 'dark', 'mysterious'],
    keywords: ['assassin', 'shadow', 'smoke', 'hood', 'daggers', 'stealth'],
    visual: {
      gradient: 'linear-gradient(135deg, #434343 0%, #000000 100%)',
      icon: '🗡️',
      color: '#434343',
      particles: ['💨', '🌑', '⚫'],
      mood: 40,
      energy: 90,
    },
  },
  {
    id: 'nature-druid',
    label: 'Forest Druid',
    description: 'Living vines as hair, bark-like skin, staff growing flowers, deer companion',
    tags: ['nature', 'magic', 'peaceful'],
    keywords: ['druid', 'nature magic', 'vines', 'forest', 'companion animal'],
    visual: {
      gradient: 'linear-gradient(135deg, #56ab2f 0%, #a8e063 100%)',
      icon: '🌿',
      color: '#56ab2f',
      particles: ['🌿', '🍃', '🦌'],
      mood: 75,
      energy: 50,
    },
  },
  {
    id: 'phoenix-guardian',
    label: 'Phoenix Guardian',
    description: 'Wings of living flame, armor with feather motifs, resurrection fire in eyes',
    tags: ['mythical', 'fire', 'guardian'],
    keywords: ['phoenix', 'fire wings', 'guardian', 'mythical', 'flame armor'],
    visual: {
      gradient: 'linear-gradient(135deg, #f12711 0%, #f5af19 100%)',
      icon: '🔥',
      color: '#f12711',
      particles: ['🔥', '🦅', '✨'],
      mood: 85,
      energy: 95,
    },
  },
  {
    id: 'ice-empress',
    label: 'Ice Empress',
    description: 'Crystalline crown, frosted gown trailing snow, commanding presence, cold elegance',
    tags: ['royal', 'ice', 'elegant'],
    keywords: ['ice queen', 'crystal crown', 'frozen', 'royal', 'elegant'],
    visual: {
      gradient: 'linear-gradient(135deg, #e0eafc 0%, #cfdef3 100%)',
      icon: '❄️',
      color: '#e0eafc',
      particles: ['❄️', '💎', '✨'],
      mood: 55,
      energy: 60,
    },
  },
  {
    id: 'clockwork-inventor',
    label: 'Clockwork Inventor',
    description: 'Brass goggles, mechanical arm, blueprint tattoos, tools orbiting like satellites',
    tags: ['steampunk', 'inventor', 'mechanical'],
    keywords: ['inventor', 'steampunk', 'mechanical', 'brass', 'goggles', 'blueprints'],
    visual: {
      gradient: 'linear-gradient(135deg, #d4a574 0%, #8b6914 100%)',
      icon: '⚙️',
      color: '#d4a574',
      particles: ['⚙️', '🔧', '💡'],
      mood: 70,
      energy: 75,
    },
  },
  {
    id: 'void-wanderer',
    label: 'Void Wanderer',
    description: 'Cloak of shifting darkness, face obscured by cosmic void, reality bending around them',
    tags: ['mysterious', 'cosmic', 'powerful'],
    keywords: ['void', 'cosmic', 'mysterious', 'reality bending', 'dark cloak'],
    visual: {
      gradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
      icon: '🌑',
      color: '#0f0c29',
      particles: ['🌌', '✨', '🔮'],
      mood: 35,
      energy: 70,
    },
  },
  {
    id: 'spirit-dancer',
    label: 'Spirit Dancer',
    description: 'Ethereal translucent form, flowing ribbons of light, barefoot, graceful movement',
    tags: ['ethereal', 'graceful', 'mystical'],
    keywords: ['spirit', 'dancer', 'ethereal', 'translucent', 'flowing', 'graceful'],
    visual: {
      gradient: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
      icon: '💃',
      color: '#ffecd2',
      particles: ['✨', '🌟', '💫'],
      mood: 80,
      energy: 65,
    },
  },
];
