/**
 * Claude Prompt Map V2 - Scene Options
 * Environment options for the prompt builder
 */

import { ClaudePromptOptionV2 } from './promptMapV2Types';

export const SCENE_OPTIONS_V2: ClaudePromptOptionV2[] = [
  {
    id: 'neon-rain-city',
    label: 'Neon-Lit Rain City',
    description: 'Towering skyscrapers reflecting in puddles, holographic billboards, flying vehicles',
    tags: ['urban', 'rain', 'cyberpunk'],
    keywords: ['cityscape', 'rain', 'neon reflections', 'skyscrapers', 'night'],
    visual: {
      gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
      icon: '🌆',
      color: '#1a1a2e',
      particles: ['💧', '✨', '🌃'],
      mood: 70,
      energy: 85,
    },
  },
  {
    id: 'bioluminescent-forest',
    label: 'Bioluminescent Forest',
    description: 'Glowing mushrooms, phosphorescent flora, ethereal mist, magical creatures lurking',
    tags: ['nature', 'magical', 'glowing'],
    keywords: ['bioluminescence', 'mystical forest', 'glowing plants', 'mist', 'enchanted'],
    visual: {
      gradient: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
      icon: '🌲',
      color: '#0f2027',
      particles: ['🍄', '✨', '🌿'],
      mood: 60,
      energy: 55,
    },
  },
  {
    id: 'floating-sky-temple',
    label: 'Floating Sky Temple',
    description: 'Ancient temple suspended in clouds, waterfalls into void, golden hour light',
    tags: ['fantasy', 'aerial', 'majestic'],
    keywords: ['floating island', 'temple ruins', 'clouds', 'waterfalls', 'golden light'],
    visual: {
      gradient: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 50%, #ff9a9e 100%)',
      icon: '⛩️',
      color: '#ffecd2',
      particles: ['☁️', '✨', '🌅'],
      mood: 80,
      energy: 65,
    },
  },
  {
    id: 'crystal-cave',
    label: 'Crystalline Cavern',
    description: 'Massive crystal formations, prismatic light refraction, underground lake',
    tags: ['underground', 'mystical', 'geometric'],
    keywords: ['crystal cave', 'gemstones', 'light refraction', 'underground', 'minerals'],
    visual: {
      gradient: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
      icon: '💎',
      color: '#a8edea',
      particles: ['💎', '✨', '🔮'],
      mood: 50,
      energy: 45,
    },
  },
  {
    id: 'desert-aurora',
    label: 'Desert Under Aurora',
    description: 'Vast sand dunes beneath dancing northern lights, ancient obelisks',
    tags: ['desert', 'surreal', 'cosmic'],
    keywords: ['desert', 'aurora borealis', 'sand dunes', 'starry sky', 'cosmic'],
    visual: {
      gradient: 'linear-gradient(135deg, #4ca1af 0%, #c4e0e5 50%, #e0c3fc 100%)',
      icon: '🏜️',
      color: '#4ca1af',
      particles: ['🌌', '✨', '⭐'],
      mood: 65,
      energy: 50,
    },
  },
  {
    id: 'underwater-ruins',
    label: 'Sunken Ruins',
    description: 'Ancient civilization underwater, coral-covered statues, shafts of sunlight',
    tags: ['underwater', 'ancient', 'mysterious'],
    keywords: ['underwater', 'ruins', 'coral', 'sunbeams', 'ancient civilization'],
    visual: {
      gradient: 'linear-gradient(135deg, #114357 0%, #29323c 50%, #485563 100%)',
      icon: '🏛️',
      color: '#114357',
      particles: ['🌊', '🐠', '💫'],
      mood: 55,
      energy: 40,
    },
  },
  {
    id: 'steampunk-workshop',
    label: 'Steampunk Workshop',
    description: 'Brass gears, steam pipes, intricate machinery, warm amber lighting',
    tags: ['steampunk', 'mechanical', 'vintage'],
    keywords: ['steampunk', 'workshop', 'brass', 'gears', 'Victorian', 'machinery'],
    visual: {
      gradient: 'linear-gradient(135deg, #b79891 0%, #94716b 100%)',
      icon: '⚙️',
      color: '#b79891',
      particles: ['⚙️', '🔧', '💨'],
      mood: 70,
      energy: 75,
    },
  },
  {
    id: 'cosmic-void',
    label: 'Cosmic Void',
    description: 'Deep space nebulas, distant galaxies, cosmic phenomena, infinite darkness',
    tags: ['space', 'cosmic', 'vast'],
    keywords: ['deep space', 'nebula', 'galaxies', 'cosmic', 'stars', 'void'],
    visual: {
      gradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
      icon: '🌌',
      color: '#0f0c29',
      particles: ['⭐', '🌟', '✨'],
      mood: 30,
      energy: 60,
    },
  },
  {
    id: 'cherry-blossom-garden',
    label: 'Cherry Blossom Garden',
    description: 'Pink petals falling, traditional Japanese garden, koi pond, peaceful zen',
    tags: ['peaceful', 'nature', 'japanese'],
    keywords: ['cherry blossoms', 'Japanese garden', 'koi pond', 'peaceful', 'spring'],
    visual: {
      gradient: 'linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)',
      icon: '🌸',
      color: '#fbc2eb',
      particles: ['🌸', '🦋', '✨'],
      mood: 75,
      energy: 35,
    },
  },
  {
    id: 'volcanic-forge',
    label: 'Volcanic Forge',
    description: 'Molten lava flows, intense heat shimmer, blacksmith working metal, sparks flying',
    tags: ['fire', 'intense', 'industrial'],
    keywords: ['volcano', 'lava', 'forge', 'heat', 'molten metal', 'sparks'],
    visual: {
      gradient: 'linear-gradient(135deg, #ff0844 0%, #ffb199 100%)',
      icon: '🌋',
      color: '#ff0844',
      particles: ['🔥', '💥', '⚡'],
      mood: 90,
      energy: 95,
    },
  },
];
